### ISSUE TITLE
Integrate Lists/Checkboxes - feature request

### ISSUE THREAD

**Issue by nextgen-networks** [PhieF/CarnetNextcloud#13]
To have this tool become a great succsessor of other note taking tools it may be fantastic to integrate a list/checkbox feature as needed for shopping lists and so on ...

If possible this should be integrated into mobile app and nc-app.

Thanks for your great work!

**Comment by PhieF** [comment]
Yep, it will be implemented

**Comment by nextgen-networks** [comment]
request can be merged with: https://github.com/PhieF/CarnetNextcloud/issues/18

**Comment by nextgen-networks** [comment]
Thanks for including lists/checkboes!
