### ISSUE TITLE
Running from docker causes UI break

### ISSUE THREAD

**Issue by paulmorabito** [PhieF/CarnetNextcloud#28]
Hi,

I am running the official nextcloud docker image and installed Carnet. The UI is broken (similar to the screenshots in issue #4 All other apps I have installed work fine. Is there a known solution for this?

**Comment by penguinsam** [comment]
Same here, NC 15 docker with Carnet 0.12 and behind nginx reverse proxy, totally not usable.

![f5c36ee9-8888-4e04-b87b-992beb11667d](https://user-images.githubusercontent.com/6859350/52172926-cc7f4480-27b4-11e9-9e94-fcf5bc2d4212.png)

**Comment by BNolet** [comment]
Yes, this is the exact same set up on my end. Except, I have two reverse proxies (reasons)

**Comment by PhieF** [comment]
Can you please press f12, refresh your page and send me a screenshot of the network tab ?

**Comment by PhieF** [comment]
Thanks ! Can you select one of the red lines and tell me the complete URL it tries to load ? It should appear on your right beginning with http or https

**Comment by BNolet** [comment]
I can tell you it's definitely trying to load resources over http

**Comment by penguinsam** [comment]
> Thanks ! Can you select one of the red lines and tell me the complete URL it tries to load ? It should appear on your right beginning with http or https

Yes, all red lines are with http

**Comment by PhieF** [comment]
Yep for some reason my php code doesn't see that the url is in https
can you try this version ?
just extract it into the apps directory of your nextcloud
[carnet-nc-v0.11.2.tar.gz](https://github.com/PhieF/CarnetNextcloud/files/2839142/carnet-nc-v0.11.2.tar.gz)

**Comment by penguinsam** [comment]
> Yep for some reason my php code doesn't see that the url is in https
> can you try this version ?
> just extract it into the apps directory of your nextcloud
> [carnet-nc-v0.11.2.tar.gz](https://github.com/PhieF/CarnetNextcloud/files/2839142/carnet-nc-v0.11.2.tar.gz)

This version works.

![image](https://user-images.githubusercontent.com/6859350/52425906-e5328600-2b37-11e9-9ce3-6f61b66427eb.png)

**Comment by PhieF** [comment]
Great ! and opening / editing a note ?

**Comment by PhieF** [comment]
Even with the new ZIP i've sent ? It's still trying in http... I will have a look tomorrow, thanks !

**Comment by BNolet** [comment]
Yeah, I wasn't even able to get to this point pre-ZIP

**Comment by PhieF** [comment]
OK thanks !

can you try this one ?

[carnet-nc-v0.12.1.zip](https://github.com/PhieF/CarnetNextcloud/files/2845381/carnet-nc-v0.12.1.zip)

**Comment by penguinsam** [comment]
> OK thanks !
> 
> can you try this one ?
> 
> [carnet-nc-v0.12.1.zip](https://github.com/PhieF/CarnetNextcloud/files/2845381/carnet-nc-v0.12.1.zip)

Tried and looks fine at this moment, display ok and create note ok

**Comment by PhieF** [comment]
ok ! great

let's close it for now :) thanks !

**Comment by BNolet** [comment]
Same result on my end, everything is looking good :ok_hand:
