### ISSUE TITLE
Carnet Nextcloud bug

### ISSUE THREAD

**Issue by pwepwe973** [PhieF/CarnetNextcloud#37]
Please report every bug related to the Android application here
https://github.com/PhieF/CarnetAndroid/

here is the nextcloud log : syntax error, unexpected '>' at /srv/dev-disk-by-label-stockage/web/nextcloud/apps/carnet/lib/Controller/NoteController.php#253

I installed notebook from the library built into nextcloud and when I go in the application ben it loads to the left and in the top left corner there is this symbol ">"
I can not use it

cordially

**Comment by pwepwe973** [comment]
hello, sorry for my english I'm french
the problem of the> has been corrected since the last update but the page always loads in loop and does not affect any note
here is the log: syntax error, unexpected '>' at /srv/dev-disk-by-label-stockage/web/nextcloud/apps/carnet/lib/Controller/NoteController.php#272

Sincerely SYLVAIN

**Comment by PhieF** [comment]
Hi, vous pouvez parler français ;) vous utilisez quelle version de PHP ? ( je traduis pour les anglophones: what version of php do you have.) mais votre anglais est tout à fait compréhensible

**Comment by pwepwe973** [comment]
bonsoir,
 j'utilise PHP 5.6.40-0+deb8u1 dans mon NAS openmediavault
merci pour l'anglais :)

**Comment by PhieF** [comment]
Bonjour, 

vous pouvez tester cette version ?

Il suffit de l'extraire dans le dossier apps/ (souvent), à la place du dossier "carnet" existant
Merci !
[carnet-nc-v0.14.0.zip](https://github.com/PhieF/CarnetNextcloud/files/2992630/carnet-nc-v0.14.0.zip)

**Comment by pwepwe973** [comment]
Bonjour 
j'ai essayé cela charge la page de présentation et une fois la page de présentation fermé il charge de nouveau en continu... je joint une capture de la page de présentation et une de la page qui charge en boucle.

![Capture d’écran_2019-03-22_14-55-05](https://user-images.githubusercontent.com/37281042/54828045-a0137f00-4cb3-11e9-93a2-50cb6916e3b6.png)
![Capture d’écran_2019-03-22_14-58-53](https://user-images.githubusercontent.com/37281042/54828064-a7d32380-4cb3-11e9-9ae3-ba2d0cfa4e87.png)

**Comment by pwepwe973** [comment]
finalement c'est bon j'ai juste actualisé la page et cela à enfin chargé  merciii je vais enfin pouvoir le tester :)

**Comment by PhieF** [comment]
ça dépend de ce que vous avez dans les paramètres de nextcloud / paramètres additionnels

il y a l'option plein écran pour carnet

**Comment by pwepwe973** [comment]
ha ok merci ben j'ai fait les modification et là c'est bon merci pour ton aide...

**Comment by PhieF** [comment]
de rien !
