### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Abfelbaum** [PhieF/CarnetNextcloud#38]
Please report every bug related to the Android application here
https://github.com/PhieF/CarnetAndroid/

**Describe the bug**
When I try to install carnet app on my nextcloud via the app store (or what it is called) I get the following error:
```An exception occurred while executing 'CREATE TABLE `oc_carnet_metadata` (`path` VARCHAR(460) NOT NULL, `metadata` LONGTEXT DEFAULT NULL, `last_modification_file` INT DEFAULT NULL, UNIQUE INDEX indexpath (`path`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes```

**To Reproduce**
1. Go to your nextcloud
2. Click on your profile picture, click on apps and choose the category over organization (don't know the english name of it)
3. Scroll down to carnet app, click on download and install

**Expected behavior**
The App should install

**Screenshots**
![grafik](https://user-images.githubusercontent.com/26802234/53983093-c0213b00-4116-11e9-8e0e-227fb1a13f31.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox
 - Version 65.0.2 (64-Bit)

**Comment by PhieF** [comment]
Can you try if this works ?

You extract it on your nextcloud app folder, if you don't know how to do it and fear breaking your install just tell me :)

[carnet-nc-vv0.13.2.tar.gz](https://github.com/PhieF/CarnetNextcloud/files/2942993/carnet-nc-vv0.13.2.tar.gz)

**Comment by PhieF** [comment]
I've just release v0.13.2 to try to fix it, can you try it ? Thanks

**Comment by ChriScho91** [comment]
For me the problem is solved!👍

Thanks for the quick fix and your awesome work!🙂

**Comment by Abfelbaum** [comment]
Fixed, thanks!
