### ISSUE TITLE
Carnet update failed

### ISSUE THREAD

**Issue by dhsc19** [PhieF/CarnetNextcloud#41]
Please report every bug related to the Android application here
https://github.com/PhieF/CarnetAndroid/

**Describe the bug**
I had a working Carnet installation.  Upon clicking the update button in the Nextcloud app page, I get this message:

An exception occurred while executing 'CREATE TABLE `oc_carnet_metadata` (`path` VARCHAR(255) NOT NULL, `metadata` LONGTEXT DEFAULT NULL, `last_modification_file` INT DEFAULT NULL, UNIQUE INDEX indexpath (`path`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Nextcloud then tries to do a system update via the browser, but continues to show this error.  Therefore, I can not get a login page.  I then had to use occ to disable the app to be able to log back in.

**To Reproduce**
1. Go to Apps page in the admin account on Nextcloud
2. Click on Update button for the Carnet app.
3. See error

**Expected behavior**
The update should complete.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: chrome
 - Version 72.0.3626.121

**Comment by PhieF** [comment]
Can you try this version of the app:

extract it on your app directory 
[carnet-nc-v0.13.4.zip](https://github.com/PhieF/CarnetNextcloud/files/2950086/carnet-nc-v0.13.4.zip)

**Comment by dhsc19** [comment]
Still getting this error:

An exception occurred while executing 'CREATE TABLE `oc_carnet_metadata` (`path` VARCHAR(200) NOT NULL, `metadata` LONGTEXT DEFAULT NULL, `last_modification_file` INT DEFAULT NULL, UNIQUE INDEX indexpath (`path`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by PhieF** [comment]
Do you use MySQL ? What is your MySQL / mariadb version ?

**Comment by dhsc19** [comment]
I'm using:

mysql  Ver 15.1 Distrib 10.1.37-MariaDB

**Comment by PhieF** [comment]
OK the max length is 191 in utf8mb4, mea culpa

try this : 

[carnet-nc-vv0.13.6.zip](https://github.com/PhieF/CarnetNextcloud/files/2957983/carnet-nc-vv0.13.6.zip)

**Comment by dhsc19** [comment]
It works!

**Comment by PhieF** [comment]
Great !

**Comment by dhsc19** [comment]
Hmmm...I just tried the 0.13.7 update that showed up on my Nextcloud apps and now I'm getting this error:

An error occured during the request. Unable to proceed.
An exception occurred while executing 'ALTER TABLE oc_carnet_metadata CHANGE `path` `path` VARCHAR(200) NOT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Detailed log as shown on the web interface:

Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_carnet_metadata CHANGE `path` `path` VARCHAR(200) NOT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
