### ISSUE TITLE
Internal server error when Carnet is enabled

### ISSUE THREAD

**Issue by ChriScho91** [PhieF/CarnetNextcloud#42]
**Describe the bug**
My Nextcloud login page just stays empty. Only the HTTP error code 500 is output in the server's logs.
As soon as I deactivate the Carnet App (via OCC Command), the page is accessible again.

I also noticed that links to shared files and folders do not work (HTTP error 500) after some time when Carnet is enabled.

**Nextcloud error log (message is displayed multiple times):**
Undefined  property: stdClass::$keyword at  /var/www/vhosts/ *** /httpdocs/nextcloud/apps/carnet/lib/Controller/NoteController.php#247

---
**and another error message**
[index] Error: Error: Call to a member function getUID() on null at
 0. <<closure>>
    OCA\Carnet\AppInfo\{closure}("*** sensitive parameters replaced ***")
 1. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Hooks/EmitterTrait.php line 99
    call_user_func_array(Closure {}, ["*** sensitive parameter replaced ***"])
 2. /var/www/vhosts/ ***  /httpdocs/nextcloud/lib/private/Hooks/PublicEmitter.php line 36
    emit("\\OC\\Files", "postWrite", ["*** sensitive parameter replaced ***"])
 3. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Files/Node/Root.php line 136
    emit("\\OC\\Files", "postWrite", ["*** sensitive parameter replaced ***"])
 4. /var/www/vhosts/ ***  /httpdocs/nextcloud/lib/private/Files/Node/Folder.php line 184
    emit("\\OC\\Files", "postWrite", ["*** sensitive parameter replaced ***"])
 5. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php line 83
    newFile("6a15-3a21-publicView.css")
 6. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Template/SCSSCacher.php line 273
    newFile("6a15-3a21-publicView.css")
 7. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Template/SCSSCacher.php line 153
    cache("/var/www/vhosts ... s", "6a15-3a21-publicView.css", "publicView.scss", OC\Files\SimpleFS\SimpleFolder {}, "/apps/files_sharing/css")
 8. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Template/CSSResourceLocator.php line 109
    process("/var/www/vhosts ... g", "css/publicView.scss", "files_sharing")
 9. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Template/CSSResourceLocator.php line 84
    cacheAndAppendScssIfExist("/var/www/vhosts ... g", "css/publicView.scss", "files_sharing")
10. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Template/ResourceLocator.php line 78
    doFind("css/publicView")
11. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/TemplateLayout.php line 292
    find(["vendor/select2 ... "])
12. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/TemplateLayout.php line 201
    findStylesheetFiles(["vendor/select2 ... "])
13. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/legacy/template.php line 211
    __construct("public", "files_sharing")
14. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php line 157
    fetchPage({displayName: "C ... }})
15. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/public/AppFramework/Http/Template/PublicTemplateResponse.php line 155
    render()
16. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 119
    render()
17. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Files_Sharin ... {}, "showShare")
18. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/public/AppFramework/App.php line 140
    main("ShareController", "showShare", OC\AppFramework\ ... {})
19. /var/www/vhosts/ *** /httpdocs/nextcloud/core/routes.php line 147
    dispatch("ShareController", "showShare")
20. <<closure>>
    {closure}("*** sensitive parameters replaced ***")
21. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(Closure {}, "*** sensitive parameter replaced ***")
22. /var/www/vhosts/ *** /httpdocs/nextcloud/lib/base.php line 987
    match("/s/o8wjLCgc364k2jN")
23. /var/www/vhosts/ *** /httpdocs/nextcloud/index.php line 42
    handleRequest()

GET /index.php/s/o8wjLCgc364k2jN
from *** at 2019-03-10T11:13:01+00:00

---
_(domain and IP deleted and replaced with *** )_

**To Reproduce**
> Activate carnet
> wait some time
> Shared links to other files are broken (HTTP error 500)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 66.0b14

**Comment by Tetrix42** [comment]
i experience the same problem when upgrading from 15.0.2 to 15.0.5.3

`{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"function":"OCA\\Carnet\\AppInfo\\{closure}","class":"OCA\\Carnet\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Hooks\/EmitterTrait.php","line":99,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Hooks\/PublicEmitter.php","line":36,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Node\/Root.php","line":136,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Node...`

**Comment by PhieF** [comment]
Hi, thanks for the report,

can you try this version of the app ? Just extract it in your apps directory or custom_apps and enable it

[carnet-nc-v0.13.4.zip](https://github.com/PhieF/CarnetNextcloud/files/2950091/carnet-nc-v0.13.4.zip)

**Comment by Tetrix42** [comment]
hey, thanks
for me it works again :+1:

**Comment by PhieF** [comment]
Great !

**Comment by ChriScho91** [comment]
Seems to be fixed for me too👍
