### ISSUE TITLE
Carnet bugs the creation of a new user account in Nextcloud

### ISSUE THREAD

**Issue by relaxmax68** [PhieF/CarnetNextcloud#43]
Please report every bug related to the Android application here
https://github.com/PhieF/CarnetAndroid/

**Describe the bug**
When a new user wants to register a new account in Nextcloud with the app «Register», some error logs appears.

**To Reproduce**
1. Go to the Nextcloud welcome page
2. Click on «register»
3. enter your email address
4. click on the link sended in your email

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser : Firefox
 - Version 65.0.1

**Comment by PhieF** [comment]
Hi,

I've just sent a new version: 0.13.6
it should fix your bug, sorry for that :)

**Comment by relaxmax68** [comment]
works perfectly now ! thanks !
