### ISSUE TITLE
possible virus or malware included?

### ISSUE THREAD

**Issue by nextgen-networks** [PhieF/CarnetNextcloud#44]
Todays Scan of ClamAV revaeled a possible virus/malware that is beeing distributed together with latest Carnet:

LOG/path:
/apps/carnet/vendor/nelexa/zip/tests/PhpZip/resources/test.apk: Andr.Malware.Smsagent-6888392-0 FOUND

----------- SCAN SUMMARY -----------
Known viruses: 9297973
Engine version: 0.100.2
Scanned directories: 
Scanned files: 
Infected files: 4
Data scanned: 
Data read: 
Time: 13765.789 sec (229 m 25 s)

Used NC version: 15.0.5

The virus/malware has also been detected in backup folders of older versions of my NC instance.
I'll list the versions mentioned in backup folder to get an idea of the timeframe we talk about:
- 15.0.1.2
- 15.0.2.0
- 15.0.4.0

**Comment by PhieF** [comment]
Hm this just seem to be the apk used for unit tests of php-zip, I don't think this is a virus but I can remove it

**Comment by nextgen-networks** [comment]
OK, this seemed to be an false positive error.
ClamAV scans made in the past few days did not contain the files as risky.

Will close this ticket - thanks for your quick response!
