### ISSUE TITLE
Naming errors.

### ISSUE THREAD

**Issue by DonTisto** [PhieF/CarnetNextcloud#50]
**Describe the bug**
After update ( or maybe some time later) i've found that images on several notes become unaccessable. While loading carnet webapp i've got 500 errors.
Firefox dev tools network(500 error example):
`index.php/apps/carnet/note/getmedia?note=untitled 12 qt.sqd&media=data/preview_SAVE_20190421_131100.jpeg.jpg`

Nextcloud journal:
`Error | PHP | Undefined index: newpath at /usr/share/nextcloud/apps/carnet/lib/Controller/NoteController.php#117`

And it seems to be error with renaming notes, because files in notes dir:
 ```
HDD_recover.sqd         Wialon.sqd
'Iptables block.sqd'    'Windows Error Codes.sqd'
 KyoceraErrorCodes.sqd  'Анимация из файлов.sqd'
 Left4Dead.sqd          'АТОЛ 90Ф.sqd'
'LVM Resize.sqd'         Бассеин.sqd
 Matiz.sqd              'Инструкция к сигнализации.sqd'
'MS SQL.sqd'             Мегафно.sqd
'net sharing.sqd'       'Полис Светки.sqd'
 quickdoc               'Полис Тёмки.sqd'
 SOX.sqd                'ТО(106780).sqd'
 Telegram.sqd           'ТО(114807).sqd'
'untitled 1 zx.sqd'     'ТО(94933).sqd'
'untitled 5 GL.sqd'      ТО.sqd
'untitled 6 NJ.sqd'      Тюмень.sqd
'untitled ah.sqd'       'Часы DT-02.sqd'
```
^proper names
But errors related to:
```
untitled 12 qt.sqd
untitled 11 Rk.sqd
untitled 10 HK.sqd
untitled 9 jM.sqd
and other

```
^ unknown names

My configuration:
NC: 15.0.7 (stable)
PHP: 7.2.17
OS: Centos 7
Selinux: enforcing
![Screenshot_2019-04-30 Carnet - Nextcloud](https://user-images.githubusercontent.com/36290045/56946529-bd096080-6b43-11e9-8ff5-279c408754a5.png)

P.S. Sorry for my bad english. And is it possible to restore notes?

**Comment by PhieF** [comment]
Hi,

Thanks for the report...

Seems weird indeed, can you try this version ? 

When you click on notes, do they load properly ?

Thanks !
[carnet-nc-v0.15.4.tar.gz](https://github.com/PhieF/CarnetNextcloud/files/3131255/carnet-nc-v0.15.4.tar.gz)

**Comment by DonTisto** [comment]
Hi,
installed new version, still no images. 
Notes opens with incorrect names and without images.

_____after several renames i've found what wrong______

But it seems to be they are ok.
Images and notes is absent only in "recent" view.
In "browser" menu they are properly named and all images loaded.
In "recent" view they are linked to previous name, not current.

May be it's depend/duplicate bug: [22](https://github.com/PhieF/CarnetNextcloud/issues/22)

**Comment by PhieF** [comment]
OK,

when you set names to notes, was it from Android or from your web browser ?

**Comment by PhieF** [comment]
I've found something 
can you try this ?

There is a bug when renaming from nextcloud, then refreshing

[carnet-nc-v0.15.4.zip](https://github.com/PhieF/CarnetNextcloud/files/3147397/carnet-nc-v0.15.4.zip)

You will perhaps have to refresh the page twice to have it fixed

**Comment by DonTisto** [comment]
Thank you! 
Now all images load properly in recent view.
I have only one error message in dev ff console [nosniff](https://developer.mozilla.org/en-US/docs/Web/HTTP/headers/X-Content-Type-Options?utm_campaign=default&utm_medium=firefox-console-errors&utm_source=mozilla) But it seems nothing broken.

**Comment by PhieF** [comment]
ok weird, thanks
