### ISSUE TITLE
nextcloud app does not open files with sqd extension

### ISSUE THREAD

**Issue by ferdiga** [PhieF/CarnetNextcloud#62]
android app creates a file with sqd extension which is well synced to nextcloud, but the nextcloud Carnet App
* does not show the file
* does not open the file if accessed via the files menu.

probably I miss read the app description which says one can retrieve the app in the browser
"Online editor as a ownCloud/NextCloud App"
Nextcloud 15.0.8
Carnet 0.16.1

**Comment by PhieF** [comment]
Hi, 

or perhaps there is a problem ;)
are they both looking at the same path ? Android is syncing in Documents/QuickNote
can you chekc in carnet settings in nextcloud side if the folder is the same ?
then go in Browser part of Carnet to check if your notes are there

**Comment by ferdiga** [comment]
yes I see the file but I can not open it in next cloud browser

**Comment by PhieF** [comment]
I'm talking about the browser part of Carnet : left column when you open the Carnet App

**Comment by ferdiga** [comment]
it's not listed in  the carnet app - left side

**Comment by PhieF** [comment]
You have sample notes instead ? Can you send me a screenshot when you open Carnet app in nextcloud ? Thanks

**Comment by ferdiga** [comment]
carnet app
![image](https://user-images.githubusercontent.com/6248560/59308968-b1609c00-8ca2-11e9-8a02-2d2ee13e69ea.png)

**Comment by ferdiga** [comment]
"Files" 

![image](https://user-images.githubusercontent.com/6248560/59309033-cfc69780-8ca2-11e9-8162-65d2af5df27f.png)

**Comment by PhieF** [comment]
Well, this isn't Carnet

You have to install the Carnet App from the Nextcloud app store

**Comment by ferdiga** [comment]
Oh, the carnet App was in the drop down menu ...., not it works

**Comment by PhieF** [comment]
OK ! I close the issue

**Comment by dombrosy** [comment]
I have the same issue. 
Desktop Carnet - I can't open the sqd file.
Android app - I can edit the notes no problem.

I have checked in my Nextcloud apps - for some reason this appears slightly lighter in colour vs all the other apps, otherwise I can't find anything else different that might solve the issue.
![Capture Carnet](https://user-images.githubusercontent.com/72285710/94979036-0baefb80-057d-11eb-91f2-5f0362ba4286.PNG)
