### ISSUE TITLE
"Unable to find Electron app" after cloning new version of Carnet

### ISSUE THREAD

**Issue by muranava** [PhieF/CarnetNextcloud#63]
Hi
After cloning latest version I can't seem to start app I get the following message:

----
Unable to find Electron app at /Users/muranava/Downloads/CarnetNextcloud-master

Cannot find module '/Users/muranava/Downloads/CarnetNextcloud-master'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- ----
I am on OSX 10.11.6

thanks

**Comment by locness3** [comment]
> Hi
> After cloning latest version I can't seem to start app I get the following message:
> 
> Unable to find Electron app at /Users/muranava/Downloads/CarnetNextcloud-master
> 
> Cannot find module '/Users/muranava/Downloads/CarnetNextcloud-master'
> Require stack:
> 
>     * /usr/local/share/.config/yarn/global/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
> 
> 
> I am on OSX 10.11.6
> 
> thanks

This issue is for PhieF/CarnetElectron

**Comment by muranava** [comment]
doh thanks!
