### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by RufioHugo** [PhieF/CarnetNextcloud#74]
Hi there!

Since first Version of Carnet Android&Nextcloud "arrived" I've got it installed ... and all the time I've had problem updating (most likely fault of my webservice) - until today the solution was;
- deactivate
- remove
- new install

But today even this didn't worked for me - message I get everytime (update & new install:
"Could not extract app carnet"

Any idea how to solve this?

Rufio

**Comment by PhieF** [comment]
Hi,

I've still not been able to fix this bug, sorry for that, I will ask nextcloud directly

**Comment by heldzz** [comment]
Hi,

problem is still valid here. Any suggestions?

**Comment by locness3** [comment]
Why closing? @RufioHugo
