### ISSUE TITLE
Selected sorting options usually not followed

### ISSUE THREAD

**Issue by tgp1994** [PhieF/CarnetNextcloud#79]
**Describe the bug**
When loading the Carnet web UI, the notes are loaded in an apparently random order. If a specific sort order is selected (such as last modified), then the notes are re-sorted. However, even though the selected sort order option is remembered, the option its self isn't applied when the notes list is reloaded. The sort order has to be re-selected in order for it to apply.

**To Reproduce**
1. Open Carnet web UI
2. Make sure a non-default sort order is selected in the view options
3. List of notes is not sorted how it should be

**Expected behavior**
Since the sort order option is already remembered (great!), I'd like to see it applied on load too.

**Screenshots**
![CarnetSort](https://user-images.githubusercontent.com/842942/64459313-71942f80-d0ac-11e9-8a37-c1b0f1b88e2e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 69.0

**Comment by PhieF** [comment]
should be fixed in 0.19,
thanks for the report

**Comment by tgp1994** [comment]
Looks good to me, thank you. I also love how fast it loads now!
