### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by ChriScho91** [PhieF/CarnetNextcloud#82]
**Describe the bug**
With activated Carnet App (Version 0.18) the Server runs in a "504 Gateway Time-out" error. After the deactivation of the App Nextcloud runs normal again.

***Server log**
upstream timed out (110: Connection timed out) while reading response header from upstream

**Nextcloud log**
Error	PHP	Undefined variable: lastmod at /var/www/vhosts/*****/httpdocs/nextcloud/apps/carnet/lib/Controller/NoteController.php#383

Error	PHP	Undefined index: metadata at /var/www/vhosts/*****/httpdocs/nextcloud/apps/carnet/lib/Controller/NoteController.php#116

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser Firefox
 - Version 70.0b8 (Beta)

**Comment by ChriScho91** [comment]
In order to be able to use my Nextcloud and Carnet at all, I once again installed Carnet version 0.17.

**Comment by timbogithub** [comment]
Can concur with this.

After upgrading to latest Carnet app, error appeared in Carnet:

"An error has occurred. Please save text...." then links in NC unresponsive. 

After closing tab, then trying to log onto NC instance, instance unresponsive for around 5 minutes, then the following error:

Gateway Timeout

The gateway did not receive a timely response from the upstream server or application.

Additionally, a 504 Gateway Timeout error was encountered while trying to use an ErrorDocument to handle the request.

NC 15, Waterfox browser. (Edge/IE unresponsive as well)

Will have to manually downgrade Carnet later to reestablish a connection to NC. 

Loving Carnet by the way! I'm sure you'll iron out the bugs. :-)

**Comment by PhieF** [comment]
Hi

thanks for the report, I've just sent a new version 0.18.1
can you check if it fixes the first issue ?

**Comment by ChriScho91** [comment]
Update to 0.18.1, but still "504 Gateway Timeout".

I noticed that I'm not able to save the note (the "Exit"-button is not clickable) and I see this error
"Error occured: TypeError: Argument 1 of Range.setEnd does not implement interface Node." (maybe connected with this issue https://github.com/PhieF/CarnetNextcloud/issues/84). After that the server runs into the "Gateway Timeout".

**Comment by PhieF** [comment]
Thx,
you don't have other info than the gateway error ? 
I've just sent another version 0.18.2 that should perhaps fixe the save bug

when you enable carnet 0.18.x your nextcloud doesn't work at all ?

**Comment by ChriScho91** [comment]
So far version 0.18.2 seems to fix the "Gateway Time-out".👍

**Comment by PhieF** [comment]
Oh nice

what about the save issue ?

**Comment by ChriScho91** [comment]
> what about the save issue ?
It also works.

**Comment by PhieF** [comment]
great ! I'm closing this then
