### ISSUE TITLE
Not possible to save new or changed notes

### ISSUE THREAD

**Issue by kaputze** [PhieF/CarnetNextcloud#84]
I can't save existing nodes after changing them or create a new one. If i want to leaf by the leaf-button (in german "verlassen") it's not possible, the Button has no functionality. 

After clicking on "leaf" i can't write any more into the node. If i now mark the text i got 
`Error occured: TypeError: Argument 1 of Range.setEnd does not implement interface Node.`

The other Buttons on the Sidebar are working without problems.

**Comment by qtrnn** [comment]
same problem here, can't save changes on note (clicking on exit do not close the current note)
also, if I check an item on a todo list on the note preview it's changed successfully

**Comment by PhieF** [comment]
OK would it be possible to create me a temporary account on one of your servers ?

**Comment by qtrnn** [comment]
@PhieF of course, how can I contact you to send your credentials?

**Comment by PhieF** [comment]
Hi,

can you send me a mail phie@phie.ovh ? Thanks

**Comment by qtrnn** [comment]
sure, just sent now ;)

**Comment by PhieF** [comment]
Thanks ! 

Can you check if this is fixed with 0.18.3 ?

Thank you

**Comment by kaputze** [comment]
Still the same problem

**Comment by PhieF** [comment]
OK
@qtrnn on your server it seems to work so, I don't understant

@kaputze can you open the dev tools (f12) network tab
then open a note, wait a few seconds and send me a screenshot with the complete network tab ? Thank you, sorry for the issue

**Comment by kaputze** [comment]
Now it works. First it don't work in Firefox, after positive testing in chromium it works also in FF. Thanks!!

**Comment by PhieF** [comment]
Great ! perhaps it has a cache issue

**Comment by kaputze** [comment]
Maybe. Thank you for your work!

**Comment by qtrnn** [comment]
tested here, works like a charm, thank you!
