### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by jookk** [PhieF/CarnetNextcloud#85]
I see this in nextcloud log:

fclose(): supplied resource is not a valid stream resource at /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#823

Only variables should be passed by reference at /var/www/nextcloud/apps/carnet/lib/Misc/CacheManager.php#98

Undefined index: metadata at /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#116

Undefined variable: lastmod at /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#383

Undefined index: nc_version at /var/www/nextcloud/apps/carnet/templates/settings.php#22

filemtime(): stat failed for settings/settings.js at /var/www/nextcloud/apps/carnet/templates/settings.php#13

Undefined variable: fullscreen at /var/www/nextcloud/apps/carnet/templates/settings.php#11

Undefined property: stdClass::$keyword at /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php#341

Undefined variable: path at /var/www/nextcloud/apps/carnet/lib/Misc/CacheManager.php#70

Nextcloud 17rc1
Php7.3
Apache2.4

**Comment by charlessteiner** [comment]
I'm getting a same error and also cannot create cards from the browser only the phone app.

[PHP] Error: Undefined property: stdClass::$keyword at /.../apps/carnet/lib/Controller/NoteController.php#341

nextcloud: 16.0.5
PHP 7.1
Apache 2.4
Firefox

**Comment by PhieF** [comment]
Hi, I've fixed many php errors with 0.18.3

Can you check if every thing works fine on your side ? Thanks for the report !

**Comment by charlessteiner** [comment]
No errors.

Thanks, PhieF!

**Comment by PhieF** [comment]
great ! thx
