### ISSUE TITLE
Web interface displaying internal server error

### ISSUE THREAD

**Issue by nealdb** [PhieF/CarnetNextcloud#89]
My previously working instance of carnet 

Now displays 

'Internal server error'

when I select it. 

This php error is showing in the log:
{"reqId":"AlPt15qrMiu2qD98xWY5","level":3,"time":"2019-11-15T19:56:54+00:00","remoteAddr":"192.168.X.XX","user":"xxxx","app":"PHP","method":"GET","url":"/index.php/apps/carnet/","message":"Undefined variable: appName at /srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/apps/carnet/lib/Controller/PageController.php#18","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","version":"15.0.13.1","id":"5dcf0376393ee"}

{"reqId":"AlPt15qrMiu2qD98hWY5","level":3,"time":"2019-11-15T19:56:54+00:00","remoteAddr":"192.168.X.XX","user":"xxxx","app":"index","method":"GET","url":"/index.php/apps/carnet/","message":{"Exception":"Error","Message":"Cannot access empty property","Code":0,"Trace":[{"function":"__construct","class":"OCA\\Carnet\\Controller\\PageController","type":"->","args":["carnet",{"__class__":"OC\\AppFramework\\Http\\Request"},"neal",{"__class__":"OC\\AllConfig"}]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":81,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[["carnet",{"__class__":"OC\\AppFramework\\Http\\Request"},"neal",{"__class__":"OC\\AllConfig"}]]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":98,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Carnet\\Controller\\PageController","__class__":"ReflectionClass"}]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":119,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Carnet\\Controller\\PageController"]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":426,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Carnet\\Controller\\PageController"]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":397,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Carnet\\Controller\\PageController"]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/private/AppFramework/App.php","line":105,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Carnet\\Controller\\PageController"]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Carnet\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"carnet.page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"carnet.page.index"}]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"carnet.page.index"}]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/lib/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/carnet/"]},{"file":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/srv/dev-disk-by-id-md-name-hadeya-HomeArray/www/nextcloud/apps/carnet/lib/Controller/PageController.php","Line":18,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","version":"15.0.13.1","id":"5dcf03763937d"}

**Comment by tgp1994** [comment]
This just started happening to me within the last week, too. I can still access my notes over the Android app, it just seems like the web interface is broken at the moment.

NC Server: 15.0.5
Carnet: 0.18.7

Whenever I try to access the webapp, these two errors always show in the log, one after the other.

**First error**
> [PHP] Error: Undefined variable: appName at /var/www/nextcloud/apps/carnet/lib/Controller/PageController.php#18
> 
> GET /nextcloud/apps/carnet/

**Second error**

> [index] Error: Error: Cannot access empty property at <<closure>>
> 
>  0. <<closure>>
>     __construct("carnet", OC\AppFramework\Http\Request {}, "glen", OC\AllConfig {})
>  1. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 81
>     newInstanceArgs(["carnet",OC\App ... }])
>  2. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 98
>     buildClass(ReflectionClass  ... "})
>  3. /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 119
>     resolve("OCA\\Carnet\\Controller\\PageController")
>  4. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 426
>     query("OCA\\Carnet\\Controller\\PageController")
>  5. /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 397
>     queryNoFallback("OCA\\Carnet\\Controller\\PageController")
>  6. /var/www/nextcloud/lib/private/AppFramework/App.php line 105
>     query("OCA\\Carnet\\Controller\\PageController")
>  7. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
>     main("OCA\\Carnet\\Controller\\PageController", "index", OC\AppFramework\ ... {}, {_route: "carnet.page.index"})
>  8. <<closure>>
>     __invoke({_route: "carnet.page.index"})
>  9. /var/www/nextcloud/lib/private/Route/Router.php line 297
>     call_user_func(OC\AppFramework\ ... {}, {_route: "carnet.page.index"})
> 10. /var/www/nextcloud/lib/base.php line 987
>     match("/apps/carnet/")
> 11. /var/www/nextcloud/index.php line 42
>     handleRequest()
> 
> GET /nextcloud/apps/carnet/

**Comment by PhieF** [comment]
Hi, thanks for your reports, what about with 0.18.10 ? It should have fixed it

**Comment by nealdb** [comment]
Just updated to 0.18.11. 

The web app now works, however when I broswe to 'Your apps'  Carnet is still showing as 0.18.7 and it is disabled, i.e the two buttons showing are 'Remove' and 'Enable'

**Comment by tgp1994** [comment]
I can confirm that updating Carnet-Nextcloud to 0.18.11 has fixed the web loading issue for me, and the app version correctly shows as 0.18.11 in Nextcloud as well.

**Comment by PhieF** [comment]
Thanks, I'm closing it
