### ISSUE TITLE
Customizing / modifying note path in NC is not possible; Carnet can only use default

### ISSUE THREAD

**Issue by 74cmonty** [PhieF/CarnetNextcloud#9]
In my understanding the default note path (in Nextcloud) is: Documents - QuickNote

Which syntax must I use in Settings if I want to change the note path to:
Dokumente - Notizen

This folder already exists in my NC account.

THX

**Comment by kauron** [comment]
When it asks for the new path it lists the old one, as `Documents/QuickNote`, so the new path should look like `Dokumente/Notizen`

**Comment by 74cmonty** [comment]
Actually that was the simple way I tried.
However it's not working, means after starting Carnet the first time in NC the directory `Documents/QuickNote` is created and some files in this directory, too.
After changing the path to `Dokumente/Notizen` everything remains unchanged, means no additional files are created in `Dokumente/Notizen`.

**Comment by PhieF** [comment]
Hi, could you please check if my last update fixed your issue ?

version 0.8.9 I've just sent, there was indeed a problem

**Comment by 74cmonty** [comment]
Issue solved.
(NC installed plugin version 0.8.10)

However there's a related issue with Carnet Android app... I'll create a separate issue for this.

**Comment by achmetinternet** [comment]
I have the issue that I changed the path to another path on my FreeNAS where Carnet had no r/w rights and now when I try to put it back to Documents/QuickNote in the field which is now apparently blank, it just starts calculating, moving its circle but nothing seems to happen.
