### ISSUE TITLE
Carnet gives a HTTP ERROR 500 after updating to 0.18.8

### ISSUE THREAD

**Issue by Omaha2002** [PhieF/CarnetNextcloud#90]
Ubuntu 18.0.4
Nextcloud 17.0.1

![image](https://user-images.githubusercontent.com/3179748/69030626-67f64480-09d8-11ea-8841-987c1a5e33ba.png)

**Errorlog Nextcloud:**

[PHP] Error: Access level to OCA\Carnet\Controller\PageController::$appName must be protected (as in class OCP\AppFramework\Controller) or weaker at /var/www/nextcloud/apps/carnet/lib/Controller/PageController.php#11

GET /apps/carnet/

**Comment by PhieF** [comment]
Should be fixed with 0.18.10, sorry :)
