### ISSUE TITLE
Autogenerated clickable <a> tag has lowercased URL

### ISSUE THREAD

**Issue by clarjon1** [PhieF/CarnetNextcloud#91]
Please report every bug related to the Android application here
https://github.com/PhieF/CarnetAndroid/

**Describe the bug**
URL preview lowercases the URL, resulting in invalid links when dealing with websites ( such as youtube ) that have case sensitive URLs

**To Reproduce**
1. Create new note
2. Paste URL into body. FOr example, https://www.youtube.com/watch?v=cGdHJ3BTh_c&t=42s
3. View note in note list, attempt to click on provided URL
4. Link takes you to https://www.youtube.com/watch?v=cgdhj3bth_c&t=42s -- an invalid/different URL

**Expected behavior**
The link slapped into the <a> tags should be the same as what's been pasted.

**Screenshots**
![image](https://user-images.githubusercontent.com/627845/69091245-e32b1b00-0a17-11ea-9ca9-c42081ef354c.png)

As seen, the clickable URL on the bottom that's autogenerated is NOT the same as the url in the body of the note

**Desktop (please complete the following information):**
- OS: Tested on Windows 10 and Archlinux (current kernel as of bug submission date)
- Browsers tested: Firefox 70, chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by locness3** [comment]
Can reproduce. OS X 10.11.6, firefox 70.0.1

**Comment by PhieF** [comment]
Thanks, it will be fixed on next release ! :)
